---
- name: Install Dotdeb repository key
  apt_key:
    url: https://www.dotdeb.org/dotdeb.gpg
    state: present

- name: Install Dotdeb repositry.
  apt_repository:
    repo: "deb http://packages.dotdeb.org jessie all"
    filename: "dotdeb"
    mode : 0644
    state: present
    update_cache: no

- name: Install Dotdeb source repositry.
  apt_repository:
    repo: "deb-src http://packages.dotdeb.org jessie all"
    filename: "dotdeb"
    mode : 0644
    state: present
    update_cache: no
